---
- name: "Add nodejs apt key"
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: "Add nodejs 13.x ppa for apt repo"
  apt_repository:
    repo: deb https://deb.nodesource.com/node_13.x bionic main
    update_cache: yes

- name: "Install nodejs"
  apt:
    update_cache: yes
    name: nodejs
    state: present

- name: "Install Dependencies"
  become: true
  apt:
    name: npm
    state: latest
    update_cache: yes

- name: Install pm2
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Creates Directory
  become: true
  file:
    path: ~/backend
    state: directory
    mode: 0755

- name: Copy backend dist files web server
  become: true
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/backend/artifact.tar.gz

- name: Unarchive
  become: true
  shell: |
    cd ~/backend
    tar xvzf artifact.tar.gz -C .

- name: "run backend"
  become: true
  shell: |
    cd ~/backend
    npm install
    pm2 stop default
    pm2 start npm --name "backend" -- run start
    cd dist
    pm2 start main.js --update-env
  args:
    chdir: /root/backend/dist
  register: shell_output
