- name: "Create backend app directory"
  file:
    path: ~/backend-app
    state: directory

- name: "unarchive files"
  unarchive:
    src: /root/project/artifact.tar.gz
    dest: ~/backend-app

- name: "run app"
  shell: |
    cd ~/backend-app  
    npm install
    pm2 stop default
    pm2 start npm -- start
