- name: "Create backend app directory"
  file:
    path: home/ubuntu/backend-app
    state: directory

- name: "copy files"
  become: true
  copy:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/backend-app

- name: "install tar"
  become: true
  apt:
    name: ["tar", "gzip"]
    state: present

- name: "Unarchive"
  become: true
  shell: |
    cd /home/ubuntu/backend-app
    tar xvzf artifact.tar.gz

- name: "run app"
  shell: |
    cd home/ubuntu/backend-app  
    npm install
    pm2 stop default
    pm2 start npm -- start
